name: CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.18.0'

      - name: Install dependencies
        run: |
          cd frontend  
          npm install
          cd ../backend  
          npm install

      - name: Start Node.js Server (Backend)
        run: |
          cd backend
          npm run start:prod &

      - name: Start React App (Frontend)
        run: |
          cd frontend
          npm run dev &

      - name: Wait for apps to start
        run: |
          sleep 10

      - name: Check if React app is running
        run: |
          curl --fail http://localhost:5173 || exit 1

      - name: Keep apps running for 10 minutes
        run: |
          sleep
